version: '3.8'

services:
  hotel-voice-ai:
    build: .
    ports:
      - "80:80"
    environment:
      # API Keys (set as needed)
      SONIOX_API_KEY: ${SONIOX_API_KEY}
      PERPLEXITY_API_KEY: ${PERPLEXITY_API_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
      CARTESIA_API_KEY: ${CARTESIA_API_KEY}
      DEEPGRAM_API_KEY: ${DEEPGRAM_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TAVUS_API_KEY: ${TAVUS_API_KEY}
      TAVUS_REPLICA_ID: ${TAVUS_REPLICA_ID}
      TAVUS_PERSONA_ID: ${TAVUS_PERSONA_ID}
      DAILY_API_KEY: ${DAILY_API_KEY}
      DAILY_ROOM_URL: ${DAILY_ROOM_URL}
      
      # Voice settings
      VOICE_TIMEOUT: ${VOICE_TIMEOUT:-120}
      MAX_CONVERSATION_DURATION: ${MAX_CONVERSATION_DURATION:-600}
      INTERRUPTION_ENABLED: ${INTERRUPTION_ENABLED:-true}
      
      # API settings
      API_BASE_URL: ${API_BASE_URL:-http://localhost:80}
      
      # Database
      DATABASE_URL: ${DATABASE_URL:-file:./database.db}
      
      # Application settings
      APP_NAME: ${APP_NAME:-Hotel Voice AI Concierge}
      APP_VERSION: ${APP_VERSION:-1.0.0}
      DEBUG: ${DEBUG:-false}
      API_HOST: ${API_HOST:-0.0.0.0}
      API_PORT: ${API_PORT:-8000}
      SECRET_KEY: ${SECRET_KEY:-change-me-in-production}
      CORS_ORIGINS: ${CORS_ORIGINS:-*}
      CORS_ALLOW_CREDENTIALS: ${CORS_ALLOW_CREDENTIALS:-true}
      
      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      LOG_FORMAT: ${LOG_FORMAT:-text}
      
      # Hotel configuration
      HOTEL_NAME: ${HOTEL_NAME:-Grand Plaza Hotel}
      HOTEL_PHONE: ${HOTEL_PHONE:-+1-555-0123}
      ROOM_SERVICE_HOURS: ${ROOM_SERVICE_HOURS:-24/7}
      GUEST_ROOM_NUMBER: ${GUEST_ROOM_NUMBER}
      
      # Order settings
      MAX_ORDER_ITEMS: ${MAX_ORDER_ITEMS:-20}
      DEFAULT_PREPARATION_TIME: ${DEFAULT_PREPARATION_TIME:-25}
      DELIVERY_TIME_BUFFER: ${DELIVERY_TIME_BUFFER:-10}
    volumes:
      # Mount database volume for persistence
      - hotel_db:/home/app/backend/database.db
      # Mount logs directory
      - hotel_logs:/home/app/backend/logs
    restart: unless-stopped

volumes:
  hotel_db:
  hotel_logs: